### ISSUE TITLE
image_size 640  then 768?

### ISSUE THREAD

**Issue by ballerburg9005** [ProGamerGov/Neural-Tile#4]
Is there any rationale for the example command first using 640 then 768 as image size?

I understand that always using 512 makes the most sense. And my 660 2GB GPU barely manages 512 if I kill Xorg.

Will the tiling be affected if I just use 512 in all 4 places?

Or do I have to use like 512, then 614 to keep the ratio?

**Comment by ProGamerGov** [comment]
@ballerburg9005 You can use whatever ratio you want. Though the closer the value is to the size of the images that the model was trained on, the more change will occur in the output image.
